name: Check Expired Applications

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  check-expired:
    runs-on: ubuntu-latest
    steps:
      - name: Check for expired applications
        run: |
          curl -X POST "${{ secrets.API_URL }}/api/supabase/check-expired" \
            -H "Authorization: Bearer ${{ secrets.API_KEY }}"
