name: Check Expired Applications

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  check-expired:
    runs-on: ubuntu-latest
    steps:
      - name: Check for expired applications
        run: |
          # Store URL parts
          BASE_URL="${{ secrets.API_URL }}"
          API_PATH="/api/supabase/check-expired/"
          FULL_URL="${BASE_URL}${API_PATH}"

          echo "Starting check-expired job..."
          echo "API endpoint: ${API_PATH}"
          echo "Full URL structure: <base_url>${API_PATH}"

          # Add -v for verbose output and -L to follow redirects
          response=$(curl -X POST "${FULL_URL}" \
            -H "Authorization: Bearer ${{ secrets.API_KEY }}" \
            -H "Content-Type: application/json" \
            -w "\n%{http_code}" \
            -v \
            -L \
            -s)

          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$ d')

          echo "Response status code: $http_code"
          echo "Response body: $body"

          if [ "$http_code" -ne 200 ]; then
            echo "Error: API call failed"
            echo "Attempted to call endpoint: ${API_PATH}"
            exit 1
          fi
